DP-840-sigint-handling
deepfield/ishell pull request #1
Opened 2018-07-03 15:51 UTC by jeff2zhang

ishell upstream source code Console exits on SIGINT, which is not what deepshell wanted. Added an exit_on_SIGINT flag to Console constructor, which is default to act exactly the same as the upstream but gives us options on how to handle SIGINT

2018-07-03 15:56 UTC, jeff2zhang commented
The stock Python readline module seems to be sufficient.
The PyPI readline v6.2.4.1 package is discontinued and replaced by gnureadline.

2018-07-05 19:28 UTC, zayfod requested changes
Two minor changes, please.

2018-07-05 19:28 UTC, zayfod commented on .gitignore
> +.idea
`.idea/` plz as this is for directories only.

2018-07-05 19:28 UTC, zayfod commented on ishell/console.py
> +    def __init__(self, prompt="Prompt", prompt_delim=">", exit_on_SIGINT=True):
please, use lower case for variables - `exit_on_sigint`.

2018-07-05 19:41 UTC, zayfod approved these changes

2018-07-05 19:44 UTC, merged